version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    networks:
      - redmine
    volumes:
      - ./redmine:/usr/src/redmine/files
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: your-favorite-password-here
      REDMINE_DB_PORT: 3306

  db:
    image: mysql:5.7
    restart: always
    networks:
      - redmine
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: your-favorite-password-here
      MYSQL_DATABASE: redmine

networks:
  redmine:
    driver: bridge
